const fs = require('fs');
const path = require('path');
const { queryAll } = require('../db/db');

const DATA_DIR = path.join(__dirname, '..', '..', 'data');
const PROGRAMS_FILE = path.join(DATA_DIR, 'programs.js');
const GRANTS_FILE = path.join(DATA_DIR, 'grants.js');
const EVENTS_FILE = path.join(DATA_DIR, 'events.js');

function parseProgramDescription(desc) {
  const result = { online: 'In-person', value: '', next: '' };
  if (!desc) return result;
  
  // Try to extract structured details from raw description
  const onlineMatch = desc.match(/Online \/ Flex:\s*([^\r\n]*)/i);
  const valueMatch = desc.match(/Network, Knowledge, Infra Value:\s*([^\r\n]*)/i);
  const nextMatch = desc.match(/Next Step:\s*([^\r\n]*)/i);
  
  if (onlineMatch) result.online = onlineMatch[1].trim();
  if (valueMatch) result.value = valueMatch[1].trim();
  if (nextMatch) result.next = nextMatch[1].trim();
  
  return result;
}

function syncAll() {
  console.log('[Sync] Starting static data export from SQLite database...');
  
  // 1. Export Programs
  const programsRows = queryAll(`
    SELECT p.*, i.title as institute_title 
    FROM programs p 
    JOIN institutes i ON p.institute_id = i.id
    WHERE p.verification_status = 'verified' AND p.publication_status = 'published'
  `);
  
  const programs = programsRows.map(row => {
    // Fetch tags
    const tags = queryAll(
      `SELECT t.name FROM tags t JOIN entity_tags et ON t.id = et.tag_id WHERE et.entity_type = 'program' AND et.entity_id = ?`,
      [row.id]
    ).map(t => t.name);

    const descDetails = parseProgramDescription(row.description);
    const hasStTag = tags.includes('st-eligible');
    
    // Remove metadata lines from description if present to clean it up for UI body
    let cleanBody = row.summary;
    if (row.description) {
      const parts = row.description.split('---');
      if (parts.length > 0 && parts[0].trim()) {
        cleanBody = parts[0].trim();
      }
    }

    return {
      id: row.slug,
      band: row.tuition_or_cost || '0-3',
      institution: row.institute_title,
      country: row.country,
      title: row.title,
      meta: `${row.city || row.country} • ${row.duration || '3 years'} • ${row.format}`,
      body: cleanBody,
      details: {
        cost: row.tuition_or_cost || 'N/A',
        online: descDetails.online || (row.format === 'online' ? '100% Online' : 'In-person'),
        assam: row.eligibility || 'ST status benefits applicable.',
        value: descDetails.value || 'General program value.',
        next: descDetails.next || 'Check website for details.',
        source: 'SQLite DB / ' + (row.source_id || 'manual')
      },
      link: row.website_url || row.application_url,
      dataAttrs: {
        category: row.region,
        format: row.format,
        stEligible: hasStTag ? 'yes' : 'maybe',
        focus: tags.filter(t => t !== 'st-eligible').join(' ')
      }
    };
  });

  const programsContent = `/**
 * Generated by sync-static.js on ${new Date().toISOString()}
 * DO NOT EDIT DIRECTLY — Update the SQLite database and run sync script.
 */

window.FILM_PATH_PROGRAMS = ${JSON.stringify(programs, null, 2)};
`;
  fs.writeFileSync(PROGRAMS_FILE, programsContent, 'utf8');
  console.log(`[Sync] Exported ${programs.length} programs to ${PROGRAMS_FILE}`);

  // 2. Export Grants (Opportunities)
  const grantsRows = queryAll(`
    SELECT * FROM opportunities 
    WHERE type = 'grant' AND verification_status = 'verified' AND publication_status = 'published'
  `);

  const grants = grantsRows.map(row => {
    const tags = queryAll(
      `SELECT t.name FROM tags t JOIN entity_tags et ON t.id = et.tag_id WHERE et.entity_type = 'opportunity' AND et.entity_id = ?`,
      [row.id]
    ).map(t => t.name);

    return {
      id: row.slug,
      title: row.title,
      org: row.org,
      amount: row.amount || 'Varies',
      eligibility: row.eligibility || 'Open',
      deadline: row.deadline || 'Annual',
      url: row.application_url || row.website_url,
      ne_notes: row.summary,
      category: row.subcategory || 'international',
      tags: tags
    };
  });

  const grantsContent = `/**
 * Generated by sync-static.js on ${new Date().toISOString()}
 * DO NOT EDIT DIRECTLY — Update the SQLite database and run sync script.
 */

window.FILM_PATH_GRANTS = ${JSON.stringify(grants, null, 2)};
`;
  fs.writeFileSync(GRANTS_FILE, grantsContent, 'utf8');
  console.log(`[Sync] Exported ${grants.length} grants to ${GRANTS_FILE}`);

  // 3. Export Events
  const eventsRows = queryAll(`
    SELECT * FROM events 
    WHERE verification_status = 'verified' AND publication_status = 'published'
  `);

  const events = eventsRows.map(row => {
    const tags = queryAll(
      `SELECT t.name FROM tags t JOIN entity_tags et ON t.id = et.tag_id WHERE et.entity_type = 'event' AND et.entity_id = ?`,
      [row.id]
    ).map(t => t.name);

    // Parse cost from description if stored there
    let cost = 'Check details';
    if (row.description) {
      const match = row.description.match(/Cost:\s*([^\r\n]*)/i);
      if (match) cost = match[1].trim();
    }

    return {
      id: row.slug,
      title: row.title,
      type: row.type || 'lab',
      when: row.deadline || 'Annual',
      cost: cost,
      eligibility: row.eligibility || 'Open',
      url: row.application_url || row.website_url,
      ne_relevance: row.summary,
      category: row.subcategory || 'labs',
      tags: tags
    };
  });

  const eventsContent = `/**
 * Generated by sync-static.js on ${new Date().toISOString()}
 * DO NOT EDIT DIRECTLY — Update the SQLite database and run sync script.
 */

window.FILM_PATH_EVENTS = ${JSON.stringify(events, null, 2)};
`;
  fs.writeFileSync(EVENTS_FILE, eventsContent, 'utf8');
  console.log(`[Sync] Exported ${events.length} events to ${EVENTS_FILE}`);

  return {
    programs: programs.length,
    grants: grants.length,
    events: events.length
  };
}

if (require.main === module) {
  try {
    syncAll();
  } catch (err) {
    console.error('[Sync] Error synchronizing static files:', err);
    process.exit(1);
  }
}

module.exports = { syncAll };
